from bisect import bisect
import sqlite3

signs = [(1, 20, "Козерог"), (2, 18, "Водолей"), (3, 20, "Рыбы"), (4, 20, "Овен"),
         (5, 21, "Телец"), (6, 21, "Близнецы"), (7, 22, "Рак"), (8, 23, "Лев"),
         (9, 23, "Дева"), (10, 23, "Весы"), (11, 22, "Скорпион"), (12, 22, "Стрелец"),
         (12, 31, "Козерог")]


def zodiac_sign(m, d):
    zn = signs[bisect(signs, (m, d))][2]
    return zn


def z_s(znak):
    con = sqlite3.connect('db/inform.db')
    cur = con.cursor()
    zn = dict()
    zn['znak'] = znak
    if zn['znak'] == "Близнецы":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM BLIZNEZI").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM BLIZNEZI").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM BLIZNEZI").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM BLIZNEZI").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM BLIZNEZI").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM BLIZNEZI").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM BLIZNEZI").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM BLIZNEZI").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM BLIZNEZI").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM BLIZNEZI").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM BLIZNEZI").fetchall()
    elif zn['znak'] == "Овен":
        zn['Знак зодиака'] = str(cur.execute("SELECT zz FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
        zn['Покровитель'] = str(cur.execute("SELECT asz FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
        zn['Отличительная черта'] = str(cur.execute("SELECT otl FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
        zn['Здоровье'] = str(cur.execute("SELECT pred FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
        zn['Плюсы'] = str(cur.execute("SELECT plus FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
        zn['Минусы'] = str(cur.execute("SELECT minus FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
        zn['Совместимость(лучшая)'] = str(cur.execute("SELECT sov FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '')
        zn['Совместимость(худшая)'] = str(cur.execute("SELECT nesov FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '')
        zn['Дело для вас'] = str(cur.execute("SELECT delo FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
        zn['Счастливые числа'] = str(cur.execute("SELECT chislo FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
        zn['Прогноз на будущее'] = str(cur.execute("SELECT prognos FROM OVEN").fetchall()).replace('[', '').replace(']', '').replace('\\n', '').replace('(', '').replace(')', '')
    elif zn['znak'] == "Телец":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM TELEZ").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM TELEZ").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM TELEZ").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM TELEZ").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM TELEZ").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM TELEZ").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM TELEZ").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM TELEZ").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM TELEZ").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM TELEZ").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM TELEZ").fetchall()
    elif zn['znak'] == "Рак":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM RAK").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM RAK").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM RAK").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM RAK").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM RAK").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM RAK").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM RAK").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM RAK").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM RAK").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM RAK").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM RAK").fetchall()
    elif zn['znak'] == "Лев":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM LEB").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM LEB").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM LEB").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM LEB").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM LEB").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM LEB").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM LEB").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM LEB").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM LEB").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM LEB").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM LEB").fetchall()
    elif zn['znak'] == "Дева":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM DEVA").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM DEVA").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM DEVA").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM DEVA").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM DEVA").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM DEVA").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM DEVA").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM DEVA").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM DEVA").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM DEVA").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM DEVA").fetchall()
    elif zn['znak'] == "Весы":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM VECI").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM VECI").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM VECI").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM VECI").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM VECI").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM VECI").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM VECI").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM VECI").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM VECI").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM VECI").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM VECI").fetchall()
    elif zn['znak'] == "Скорпион":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM SKORPION").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM SKORPION").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM SKORPION").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM SKORPION").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM SKORPION").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM SKORPION").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM SKORPION").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM SKORPION").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM SKORPION").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM SKORPION").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM SKORPION").fetchall()
    elif zn['znak'] == "Стрелец":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM CTRELEZ").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM CTRELEZ").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM CTRELEZ").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM CTRELEZ").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM CTRELEZ").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM CTRELEZ").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM CTRELEZ").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM CTRELEZ").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM CTRELEZ").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM CTRELEZ").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM CTRELEZ").fetchall()
    elif zn['znak'] == "Рак":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM RAK").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM RAK").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM RAK").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM RAK").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM RAK").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM RAK").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM RAK").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM RAK").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM RAK").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM RAK").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM RAK").fetchall()
    elif zn['znak'] == "Козерог":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM KOZA").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM KOZA").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM KOZA").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM KOZA").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM KOZA").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM KOZA").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM KOZA").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM KOZA").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM KOZA").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM KOZA").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM KOZA").fetchall()
    elif zn['znak'] == "Водолей":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM VODOLEI").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM VODOLEI").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM VODOLEI").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM VODOLEI").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM VODOLEI").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM VODOLEI").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM VODOLEI").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM VODOLEI").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM VODOLEI").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM VODOLEI").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM VODOLEI").fetchall()
    elif zn['znak'] == "Рыбы":
        zn['Знак зодиака'] = cur.execute("SELECT zz FROM RIBA").fetchall()
        zn['Покровитель'] = cur.execute("SELECT asz FROM RIBA").fetchall()
        zn['Отличительная черта'] = cur.execute("SELECT otl FROM RIBA").fetchall()
        zn['Здоровье'] = cur.execute("SELECT pred FROM RIBA").fetchall()
        zn['Плюсы'] = cur.execute("SELECT plus FROM RIBA").fetchall()
        zn['Минусы'] = cur.execute("SELECT minus FROM RIBA").fetchall()
        zn['Совместимость(лучшая)'] = cur.execute("SELECT sov FROM RIBA").fetchall()
        zn['Совместимость(худшая)'] = cur.execute("SELECT nesov FROM RIBA").fetchall()
        zn['Дело для вас'] = cur.execute("SELECT delo FROM RIBA").fetchall()
        zn['Счастливые числа'] = cur.execute("SELECT chislo FROM RIBA").fetchall()
        zn['Прогноз на будущее'] = cur.execute("SELECT prognos FROM RIBA").fetchall()
    return zn

a = z_s(zodiac_sign(2, 25))
for i in a.keys():
    print(i, a[i])
